# Generated by Django 4.0.6 on 2022-08-11 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aiproject', '0004_dh_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='中文標題')),
                ('etitle', models.CharField(default='', max_length=200, verbose_name='英文標題')),
                ('jtitle', models.CharField(default='', max_length=200, verbose_name='日文標題')),
                ('editor', models.CharField(max_length=100, verbose_name='編輯')),
                ('content', models.TextField(verbose_name='內容')),
                ('url', models.CharField(max_length=200, verbose_name='來源網址')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiproject.postcat')),
            ],
        ),
    ]
