# Generated by Django 4.0.6 on 2022-08-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiproject', '0005_postcat_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='etitle',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='英文標題'),
        ),
        migrations.AlterField(
            model_name='post',
            name='jtitle',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='日文標題'),
        ),
    ]
