# Generated by Django 4.0.6 on 2022-08-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiproject', '0006_alter_post_etitle_alter_post_jtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='editor',
            field=models.CharField(max_length=200, verbose_name='編輯'),
        ),
    ]
