# Generated by Django 4.0.6 on 2022-08-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiproject', '0007_alter_post_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=models.CharField(default='N/A', max_length=200, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.CharField(default='N/A', max_length=200, verbose_name='編輯事項'),
        ),
        migrations.AlterField(
            model_name='post',
            name='editor',
            field=models.CharField(max_length=200, verbose_name='責任編輯'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(default='N/A', max_length=200, verbose_name='來源網址'),
        ),
    ]
