# Generated by Django 4.0.6 on 2022-08-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiproject', '0008_post_abstract_post_comment_alter_post_editor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名稱')),
            ],
        ),
    ]
