# Generated by Django 4.0.6 on 2022-08-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiproject', '0009_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名稱')),
            ],
        ),
        migrations.DeleteModel(
            name='keywords',
        ),
    ]
