# Generated by Django 4.0.6 on 2022-08-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiproject', '0010_keyword_delete_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keyword',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='關鍵字'),
        ),
    ]
