# Generated by Django 4.0.6 on 2022-08-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiproject', '0011_post_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='圖片說明')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='照片檔案')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='新增日期')),
            ],
        ),
    ]
